name: my_shopping
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/email.png
    - assets/lock.png
    - assets/telephone.png
    - assets/user.png
    - assets/first.png
    - assets/basket.png
    - assets/cap.png
    - assets/watch.jpg
    - assets/belt.png
    - assets/bag.png
    - assets/tshirt.png
    - assets/thorjacket.png
    - assets/petite.jpg
    - assets/woment.jpg
    - assets/fulljacket.jpg
    - assets/cheche.jpg
    - assets/full.jpg
    - assets/fullll.jpg
    - assets/footo.png
    - assets/footf.png
    - assets/foott.png
    - assets/blazzer.png
    - assets/jbl.jpg
    - assets/gadgets.png
    - assets/headphonet.png
    - assets/denim.jpg
    - assets/sari.png
    - assets/mensl.png
    - assets/hills.png
    - assets/pumashoes.png
    - assets/kurta.png
    - assets/student.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: raleway_bold
       fonts:
         - asset: fonts/raleway_bold.ttf
     - family: Montserrat
       fonts:
         - asset: fonts/Montserrat-Light.ttf
     - family: RalewaySemiBold
       fonts:
         - asset: fonts/raleway_semibold.ttf
     - family: Montserrat_Bold
       fonts:
         - asset: fonts/Montserrat-SemiBold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
